import{S as m,i as c}from"./assets/vendor-0fc460d7.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();function h(s){const r="https://pixabay.com/api",o="45177061-dd77212e3ebf23708a837f031",a=new URLSearchParams({key:o,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0});return fetch(`${r}?${a}`).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()})}function y(s){const r=new m(".gallery-list a",{captions:!0,captionsData:"alt",captionDelay:250}),o=document.querySelector(".gallery-list"),a=s.hits.map(({webformatURL:e,largeImageURL:t,tags:i,likes:u,views:d,comments:p,downloads:f})=>`<li class="card-item">
<a class="gallery-link"  href=${t}>
<img class="gallery-image"
src=${e} alt=${i} /></a>
   <div class="card-body">
     <p class="card-text">likes<span class="card-value"> ${u}</span></p>
     <p class="card-text">views<span class="card-value"> ${d}</span></p>
     <p class="card-text">comments<span class="card-value"> ${p}</span></p>
     <p class="card-text">downloads<span class="card-value"> ${f}</span></p>
</li>`).join("");o.innerHTML=a,r.refresh()}const g=document.querySelector(".search-form"),l=document.querySelector(".gallery-list"),n=document.querySelector(".loader");g.addEventListener("submit",L);function L(s){s.preventDefault(),l.innerHTML="",n.classList.remove("hidden");const r=s.currentTarget,o=r.elements.query.value.trim().toLowerCase();h(o).then(a=>{if(a.total===0){c.error({position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"}),n.classList.add("hidden");return}if(o===""){c.error({position:"topRight",message:"Please fill the input"}),n.classList.add("hidden");return}else y(a);n.classList.add("hidden")}).catch(v).finally(()=>r.reset())}function v(s){l.innerHTML="",c.error({position:"topRight",message:`${s}`})}
//# sourceMappingURL=commonHelpers.js.map
